# Generated by Django 5.1.5 on 2025-07-22 15:23

import django.db.models.deletion
import relations.utilities.validation_helpers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "__first__"),
        ("engagements", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Partner",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partners",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partner",
                "verbose_name_plural": "Partners",
            },
        ),
        migrations.CreateModel(
            name="CustomRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=50)),
                ("label", models.CharField(max_length=100)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_roles",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "unique_together": {("tenant", "key")},
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "partner_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="relations.partner",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "organization_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("relations.partner",),
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "partner_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="relations.partner",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("relations.partner",),
        ),
        migrations.CreateModel(
            name="RelationReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("person", "Person"),
                            ("organization", "Organization"),
                            ("workitem", "WorkItem"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="relations.partner",
                    ),
                ),
                (
                    "workitem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="engagements.workitem",
                    ),
                ),
            ],
            bases=(
                models.Model,
                relations.utilities.validation_helpers.SingleReferenceValidatorMixin,
                relations.utilities.validation_helpers.TypeInstanceValidatorMixin,
            ),
        ),
        migrations.CreateModel(
            name="Relation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "relation_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relations",
                        to="core.tenant",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relation_sources",
                        to="relations.relationreference",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relation_targets",
                        to="relations.relationreference",
                    ),
                ),
            ],
            bases=(
                models.Model,
                relations.utilities.validation_helpers.TenantValidatorMixin,
            ),
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "system_role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("super_user", "Super User"),
                            ("admin", "Admin"),
                            ("user", "User"),
                            ("readonly", "Read Only"),
                            ("tenant_owner", "Tenant Owner"),
                            ("tenant_employee", "Tenant Employee"),
                            ("tenant_admin", "Tenant Admin"),
                            ("contact_info", "Contact Info"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "custom_role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="relations.customrole",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="relations.relationreference",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="core.tenant",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="relationreference",
            index=models.Index(fields=["type"], name="relations_r_type_3391e6_idx"),
        ),
        migrations.AddIndex(
            model_name="relationreference",
            index=models.Index(
                fields=["partner"], name="relations_r_partner_79fda7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="relationreference",
            index=models.Index(
                fields=["workitem"], name="relations_r_workite_f7e478_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="relationreference",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("partner__isnull", False), ("workitem__isnull", True)),
                    models.Q(("partner__isnull", True), ("workitem__isnull", False)),
                    _connector="OR",
                ),
                name="exactly_one_reference",
            ),
        ),
        migrations.AddIndex(
            model_name="relation",
            index=models.Index(
                fields=["tenant"], name="relations_r_tenant__339bf2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="relation",
            index=models.Index(
                fields=["relation_type"], name="relations_r_relatio_04f5b8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="relation",
            index=models.Index(
                fields=["source"], name="relations_r_source__329f85_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="relation",
            index=models.Index(
                fields=["target"], name="relations_r_target__ed625d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="role",
            constraint=models.UniqueConstraint(
                fields=("tenant", "target", "system_role", "custom_role"),
                name="unique_role_per_target",
            ),
        ),
    ]
