# Generated by Django 5.1.5 on 2025-07-08 20:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Partner",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partners",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partner",
                "verbose_name_plural": "Parties",
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "partner_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="relations.partner",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "organization_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("relations.partner",),
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "partner_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="relations.partner",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("relations.partner",),
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role_type",
                    models.CharField(
                        choices=[
                            ("super_user", "Super User"),
                            ("admin", "Admin"),
                            ("user", "User"),
                            ("readonly", "Read Only"),
                            ("tenant", "Tenant"),
                            ("tenant_owner", "Tenant Owner"),
                            ("tenant_manager", "Tenant Manager"),
                            ("tenant_admin", "Tenant Admin"),
                            ("tenant_billing", "Tenant Billing"),
                            ("tenant_employee", "Tenant Employee"),
                            ("tenant_readonly", "Tenant Read Only"),
                            ("contact_info", "Contact Info"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="relations.partner",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
