# Generated by Django 5.1.5 on 2025-08-04 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_initial"),
        ("engagements", "0002_initial"),
        ("relations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.role",
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="partners",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="relation",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="relation",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.role"
            ),
        ),
        migrations.AddField(
            model_name="relation",
            name="source_partner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="source_relations",
                to="relations.partner",
            ),
        ),
        migrations.AddField(
            model_name="relation",
            name="source_workitem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="source_relations",
                to="engagements.workitem",
            ),
        ),
        migrations.AddField(
            model_name="relation",
            name="target_partner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="target_relations",
                to="relations.partner",
            ),
        ),
        migrations.AddField(
            model_name="relation",
            name="target_workitem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="target_relations",
                to="engagements.workitem",
            ),
        ),
        migrations.AddField(
            model_name="relation",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="relations",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="relation",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="relation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="relations.relation",
            ),
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "partner_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="relations.partner",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "organization_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["name"], name="relations_o_name_c324e0_idx"),
                    models.Index(
                        fields=["organization_number"],
                        name="relations_o_organiz_40aa03_idx",
                    ),
                ],
            },
            bases=("relations.partner",),
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "partner_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="relations.partner",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["first_name", "last_name"],
                        name="relations_p_first_n_b54196_idx",
                    ),
                    models.Index(fields=["email"], name="relations_p_email_78e7bf_idx"),
                    models.Index(
                        fields=["last_name", "first_name"],
                        name="relations_p_last_na_7291f0_idx",
                    ),
                ],
            },
            bases=("relations.partner",),
        ),
        migrations.AddIndex(
            model_name="partner",
            index=models.Index(
                fields=["tenant"], name="relations_p_tenant__2098b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partner",
            index=models.Index(
                fields=["created_at"], name="relations_p_created_a06b09_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partner",
            index=models.Index(
                fields=["updated_at"], name="relations_p_updated_4f0d98_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="relation",
            index=models.Index(
                fields=["tenant", "source_partner"],
                name="relations_r_tenant__a4473f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="relation",
            index=models.Index(
                fields=["tenant", "source_workitem"],
                name="relations_r_tenant__d01e39_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="relation",
            index=models.Index(
                fields=["tenant", "target_partner"],
                name="relations_r_tenant__60da8f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="relation",
            index=models.Index(
                fields=["tenant", "target_workitem"],
                name="relations_r_tenant__dd115d_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="relation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("source_partner__isnull", False),
                        ("source_workitem__isnull", True),
                    ),
                    models.Q(
                        ("source_partner__isnull", True),
                        ("source_workitem__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="exactly_one_source_reference",
            ),
        ),
        migrations.AddConstraint(
            model_name="relation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("target_partner__isnull", False),
                        ("target_workitem__isnull", True),
                    ),
                    models.Q(
                        ("target_partner__isnull", True),
                        ("target_workitem__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="exactly_one_target_reference",
            ),
        ),
        migrations.AddConstraint(
            model_name="relation",
            constraint=models.UniqueConstraint(
                fields=(
                    "tenant",
                    "source_type",
                    "source_partner",
                    "source_workitem",
                    "target_type",
                    "target_partner",
                    "target_workitem",
                    "role",
                ),
                name="unique_relation_per_source_target_role",
            ),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["tenant"], name="relations_a_tenant__5ec856_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["relation"], name="relations_a_relatio_cba479_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["created_at"], name="relations_a_created_c38515_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["tenant", "relation"], name="relations_a_tenant__82840c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="assignment",
            unique_together={("relation",)},
        ),
    ]
