# Generated by Django 5.1.5 on 2025-07-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "__first__"),
        ("relations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="role",
            name="unique_role_per_target",
        ),
        migrations.AddConstraint(
            model_name="role",
            constraint=models.UniqueConstraint(
                condition=models.Q(("system_role__isnull", False)),
                fields=("tenant", "target", "system_role"),
                name="unique_system_role_per_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="role",
            constraint=models.UniqueConstraint(
                condition=models.Q(("custom_role__isnull", False)),
                fields=("tenant", "target", "custom_role"),
                name="unique_custom_role_per_target",
            ),
        ),
    ]
