# Generated by Django 5.1.5 on 2025-07-11 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("relations", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="partner",
            options={"verbose_name": "Partner", "verbose_name_plural": "Partners"},
        ),
    ]
