# Generated by Django 5.1.5 on 2025-07-27 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_initial"),
        ("engagements", "0002_initial"),
        ("relations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.role",
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="partners",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="relation",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="relation",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.role"
            ),
        ),
        migrations.AddField(
            model_name="relation",
            name="source_partner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="source_relations",
                to="relations.partner",
            ),
        ),
        migrations.AddField(
            model_name="relation",
            name="source_workitem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="source_relations",
                to="engagements.workitem",
            ),
        ),
        migrations.AddField(
            model_name="relation",
            name="target_partner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="target_relations",
                to="relations.partner",
            ),
        ),
        migrations.AddField(
            model_name="relation",
            name="target_workitem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="target_relations",
                to="engagements.workitem",
            ),
        ),
        migrations.AddField(
            model_name="relation",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="relations",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="relation",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(fields=["name"], name="relations_o_name_c324e0_idx"),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(
                fields=["organization_number"], name="relations_o_organiz_40aa03_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(
                fields=["first_name", "last_name"],
                name="relations_p_first_n_b54196_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(fields=["email"], name="relations_p_email_78e7bf_idx"),
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(
                fields=["last_name", "first_name"],
                name="relations_p_last_na_7291f0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="partner",
            index=models.Index(
                fields=["tenant"], name="relations_p_tenant__2098b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partner",
            index=models.Index(
                fields=["created_at"], name="relations_p_created_a06b09_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partner",
            index=models.Index(
                fields=["updated_at"], name="relations_p_updated_4f0d98_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="relation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("source_partner__isnull", False),
                        ("source_workitem__isnull", True),
                    ),
                    models.Q(
                        ("source_partner__isnull", True),
                        ("source_workitem__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="exactly_one_source_reference",
            ),
        ),
        migrations.AddConstraint(
            model_name="relation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("target_partner__isnull", False),
                        ("target_workitem__isnull", True),
                    ),
                    models.Q(
                        ("target_partner__isnull", True),
                        ("target_workitem__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="exactly_one_target_reference",
            ),
        ),
    ]
