# Generated by Django 5.1.5 on 2025-07-27 19:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_add_user_tenant_entity_types"),
        ("engagements", "0002_initial"),
        ("relations", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="relation",
            index=models.Index(
                fields=["tenant", "source_partner"],
                name="relations_r_tenant__a4473f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="relation",
            index=models.Index(
                fields=["tenant", "source_workitem"],
                name="relations_r_tenant__d01e39_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="relation",
            index=models.Index(
                fields=["tenant", "target_partner"],
                name="relations_r_tenant__60da8f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="relation",
            index=models.Index(
                fields=["tenant", "target_workitem"],
                name="relations_r_tenant__dd115d_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="relation",
            constraint=models.UniqueConstraint(
                fields=(
                    "tenant",
                    "source_type",
                    "source_partner",
                    "source_workitem",
                    "target_type",
                    "target_partner",
                    "target_workitem",
                    "role",
                ),
                name="unique_relation_per_source_target_role",
            ),
        ),
    ]
