# Generated by Django 5.1.5 on 2025-07-22 15:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relations", "0002_remove_role_unique_role_per_target_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relationreference",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
