# Generated by Django 5.1.5 on 2025-07-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relations", "0003_alter_relationreference_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="system_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("super_user", "Super User"),
                    ("admin", "Admin"),
                    ("user", "User"),
                    ("readonly", "Read Only"),
                    ("tenant_owner", "Tenant Owner"),
                    ("tenant_employee", "Tenant Employee"),
                    ("tenant_admin", "Tenant Admin"),
                    ("contact_info", "Contact Info"),
                    ("customer", "Customer"),
                    ("vendor", "Vendor"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
