# Generated by Django 5.1.5 on 2025-07-27 20:07

import django.db.models.deletion
import relations.utilities.validation_helpers
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_add_user_tenant_entity_types"),
        ("relations", "0003_relation_relations_r_tenant__a4473f_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "relation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="relations.relation",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="core.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tenant"], name="relations_a_tenant__5ec856_idx"
                    ),
                    models.Index(
                        fields=["relation"], name="relations_a_relatio_cba479_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="relations_a_created_c38515_idx"
                    ),
                    models.Index(
                        fields=["tenant", "relation"],
                        name="relations_a_tenant__82840c_idx",
                    ),
                ],
                "unique_together": {("relation",)},
            },
            bases=(
                models.Model,
                relations.utilities.validation_helpers.TenantValidatorMixin,
            ),
        ),
    ]
