# Generated by Django 5.1.5 on 2025-07-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "__first__"),
        ("engagements", "0003_activitylog_engagements_tenant__4a28de_idx_and_more"),
        ("relations", "0004_alter_role_system_role"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(fields=["name"], name="relations_o_name_c324e0_idx"),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(
                fields=["organization_number"], name="relations_o_organiz_40aa03_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partner",
            index=models.Index(
                fields=["tenant"], name="relations_p_tenant__2098b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partner",
            index=models.Index(
                fields=["created_at"], name="relations_p_created_a06b09_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partner",
            index=models.Index(
                fields=["updated_at"], name="relations_p_updated_4f0d98_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(
                fields=["first_name", "last_name"],
                name="relations_p_first_n_b54196_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(fields=["email"], name="relations_p_email_78e7bf_idx"),
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(
                fields=["last_name", "first_name"],
                name="relations_p_last_na_7291f0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="relation",
            index=models.Index(
                fields=["tenant", "relation_type"],
                name="relations_r_tenant__6d1928_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="relation",
            index=models.Index(
                fields=["source", "target"], name="relations_r_source__4d6bd2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="relation",
            index=models.Index(
                fields=["tenant", "source"], name="relations_r_tenant__5cf6ad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="relation",
            index=models.Index(
                fields=["tenant", "target"], name="relations_r_tenant__2ba6e8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="relationreference",
            index=models.Index(
                fields=["type", "partner"], name="relations_r_type_e6cd7e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="relationreference",
            index=models.Index(
                fields=["type", "workitem"], name="relations_r_type_58c185_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(
                fields=["tenant"], name="relations_r_tenant__349edd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(
                fields=["target"], name="relations_r_target__306c9b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(
                fields=["system_role"], name="relations_r_system__fe0799_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(
                fields=["custom_role"], name="relations_r_custom__f9cf57_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(
                fields=["tenant", "system_role"], name="relations_r_tenant__7a83a1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(
                fields=["tenant", "custom_role"], name="relations_r_tenant__cf27b5_idx"
            ),
        ),
    ]
