# Generated by Django 5.1.5 on 2025-08-03 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("relations", "0004_assignment"),
    ]

    operations = [
        migrations.DeleteModel(name="Partner"),
        migrations.DeleteModel(name="Person"), 
        migrations.DeleteModel(name="Organization"),
    ]
