# Generated by Django 5.1.5 on 2025-07-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relations", "0005_organization_relations_o_name_c324e0_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relation",
            name="relation_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("customer", "Customer"),
                    ("vendor", "Vendor"),
                    ("supplier", "Supplier"),
                    ("partner", "Partner"),
                    ("competitor", "Competitor"),
                    ("member_of", "Member Of"),
                    ("employee_of", "Employee Of"),
                    ("owner_of", "Owner Of"),
                    ("assigned_to", "Assigned To"),
                    ("reported_by", "Reported By"),
                    ("approved_by", "Approved By"),
                    ("reviewed_by", "Reviewed By"),
                    ("contact_for", "Contact For"),
                    ("client_for", "Client For"),
                    ("blocks", "Blocks"),
                    ("depends_on", "Depends On"),
                    ("related_to", "Related To"),
                    ("duplicate_of", "Duplicate Of"),
                    ("parent_of", "Parent Of"),
                    ("child_of", "Child Of"),
                    ("contacts", "Contacts"),
                    ("works_with", "Works With"),
                    ("reports_to", "Reports To"),
                    ("manages", "Manages"),
                    ("collaborates_with", "Collaborates With"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
