# Generated by Django 5.1.5 on 2025-07-24 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relations", "0010_alter_role_system_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="target",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="relations.partner"
            ),
        ),
    ]
