# Generated by Django 5.1.5 on 2025-08-03 14:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0004_update_auditlog_tenant_cascade"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.role",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partners",
                        to="core.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Partner",
                "verbose_name_plural": "Partners",
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "partner_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="partners.partner",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "organization_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["name"], name="partners_or_name_387ea9_idx"),
                    models.Index(
                        fields=["organization_number"],
                        name="partners_or_organiz_a3526e_idx",
                    ),
                ],
            },
            bases=("partners.partner",),
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "partner_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="partners.partner",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["first_name", "last_name"],
                        name="partners_pe_first_n_641236_idx",
                    ),
                    models.Index(fields=["email"], name="partners_pe_email_e23701_idx"),
                    models.Index(
                        fields=["last_name", "first_name"],
                        name="partners_pe_last_na_21b109_idx",
                    ),
                ],
            },
            bases=("partners.partner",),
        ),
        migrations.AddIndex(
            model_name="partner",
            index=models.Index(
                fields=["tenant"], name="partners_pa_tenant__bcb125_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partner",
            index=models.Index(
                fields=["created_at"], name="partners_pa_created_2a97d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partner",
            index=models.Index(
                fields=["updated_at"], name="partners_pa_updated_669fbd_idx"
            ),
        ),
    ]
