# Generated by Django 5.1.5 on 2025-08-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="partner",
            name="created_by",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="partner",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="partner",
            name="updated_by",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
