# Generated by Django 5.1.5 on 2025-08-04 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("partners", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="partner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(fields=["name"], name="partners_or_name_387ea9_idx"),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(
                fields=["organization_number"], name="partners_or_organiz_a3526e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(
                fields=["first_name", "last_name"],
                name="partners_pe_first_n_641236_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(fields=["email"], name="partners_pe_email_e23701_idx"),
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(
                fields=["last_name", "first_name"],
                name="partners_pe_last_na_21b109_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="partner",
            index=models.Index(
                fields=["tenant"], name="partners_pa_tenant__bcb125_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partner",
            index=models.Index(
                fields=["created_at"], name="partners_pa_created_2a97d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partner",
            index=models.Index(
                fields=["updated_at"], name="partners_pa_updated_669fbd_idx"
            ),
        ),
    ]
