# Generated by Django 5.1.5 on 2025-07-22 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "__first__"),
        ("engagements", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="activitylog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="attachment",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="attachment",
            name="uploaded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "workitem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="engagements.workitem",
                    ),
                ),
                ("case_reference", models.CharField(max_length=100, unique=True)),
                ("legal_area", models.CharField(max_length=100)),
                ("court_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("engagements.workitem",),
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "workitem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="engagements.workitem",
                    ),
                ),
                ("job_code", models.CharField(max_length=50, unique=True)),
                ("assigned_team", models.CharField(max_length=100)),
                (
                    "estimated_hours",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("engagements.workitem",),
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "workitem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="engagements.workitem",
                    ),
                ),
                (
                    "ticket_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "reported_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "urgency",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("engagements.workitem",),
        ),
        migrations.AddField(
            model_name="workitem",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_work_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="workitem",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="work_items",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="attachment",
            name="work_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="engagements.workitem",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="work_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="engagements.workitem",
            ),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="work_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activity_log",
                to="engagements.workitem",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="work_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="engagements.workitem",
            ),
        ),
        migrations.AddField(
            model_name="workitempartnerrole",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="workitempartnerrole",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="work_item_partner_roles",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="workitempartnerrole",
            name="work_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="partner_roles",
                to="engagements.workitem",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="assignment",
            unique_together={("work_item", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="workitempartnerrole",
            unique_together={
                ("work_item", "content_type", "object_id", "role", "tenant")
            },
        ),
    ]
