# Generated by Django 5.1.5 on 2025-07-11 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engagements", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workitem",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="work_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activity_log",
                to="engagements.workitem",
            ),
        ),
    ]
