# Generated by Django 5.1.5 on 2025-07-22 15:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "__first__"),
        ("engagements", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["tenant"], name="engagements_tenant__4a28de_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["work_item"], name="engagements_work_it_63c54c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(fields=["user"], name="engagements_user_id_d47402_idx"),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["activity_type"], name="engagements_activit_37ea37_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["created_at"], name="engagements_created_287c11_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["tenant", "work_item"], name="engagements_tenant__a1149f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["user", "activity_type"], name="engagements_user_id_9d07b6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["work_item", "created_at"],
                name="engagements_work_it_1faaed_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["work_item"], name="engagements_work_it_64c1f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(fields=["user"], name="engagements_user_id_9cabf3_idx"),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["assigned_by"], name="engagements_assigne_b947f3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["assigned_at"], name="engagements_assigne_5642d9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["user", "assigned_at"], name="engagements_user_id_6883a0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attachment",
            index=models.Index(
                fields=["tenant"], name="engagements_tenant__2c289f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attachment",
            index=models.Index(
                fields=["work_item"], name="engagements_work_it_4a0ab0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attachment",
            index=models.Index(
                fields=["uploaded_by"], name="engagements_uploade_2b66df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attachment",
            index=models.Index(
                fields=["filename"], name="engagements_filenam_bd370d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attachment",
            index=models.Index(
                fields=["mime_type"], name="engagements_mime_ty_256ab9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attachment",
            index=models.Index(
                fields=["tenant", "work_item"], name="engagements_tenant__5b9c3c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attachment",
            index=models.Index(
                fields=["uploaded_by", "created_at"],
                name="engagements_uploade_326b4a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["tenant"], name="engagements_tenant__d509b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["work_item"], name="engagements_work_it_eff6ac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["author"], name="engagements_author__8af639_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["created_at"], name="engagements_created_fe993f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["tenant", "work_item"], name="engagements_tenant__81cca4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["author", "created_at"], name="engagements_author__24af41_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workitem",
            index=models.Index(
                fields=["tenant"], name="engagements_tenant__d01a32_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workitem",
            index=models.Index(fields=["status"], name="engagements_status_8eecb9_idx"),
        ),
        migrations.AddIndex(
            model_name="workitem",
            index=models.Index(
                fields=["category"], name="engagements_categor_47e530_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workitem",
            index=models.Index(
                fields=["priority"], name="engagements_priorit_0b2a80_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workitem",
            index=models.Index(
                fields=["created_by"], name="engagements_created_fb5766_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workitem",
            index=models.Index(
                fields=["is_deleted"], name="engagements_is_dele_bfbc8c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workitem",
            index=models.Index(
                fields=["created_at"], name="engagements_created_f6f079_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workitem",
            index=models.Index(
                fields=["deadline"], name="engagements_deadlin_5fa081_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workitem",
            index=models.Index(
                fields=["tenant", "status"], name="engagements_tenant__6b6101_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workitem",
            index=models.Index(
                fields=["tenant", "category"], name="engagements_tenant__b8e7ff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workitem",
            index=models.Index(
                fields=["tenant", "priority"], name="engagements_tenant__363847_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workitem",
            index=models.Index(
                fields=["tenant", "is_deleted"], name="engagements_tenant__fc5549_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workitem",
            index=models.Index(
                fields=["status", "priority"], name="engagements_status_f28b5f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workitem",
            index=models.Index(
                fields=["category", "status"], name="engagements_categor_aad048_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workitempartnerrole",
            index=models.Index(
                fields=["tenant"], name="engagements_tenant__fbb641_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workitempartnerrole",
            index=models.Index(
                fields=["work_item"], name="engagements_work_it_b49bbd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workitempartnerrole",
            index=models.Index(fields=["role"], name="engagements_role_51cc68_idx"),
        ),
        migrations.AddIndex(
            model_name="workitempartnerrole",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="engagements_content_b6f9e9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workitempartnerrole",
            index=models.Index(
                fields=["tenant", "work_item"], name="engagements_tenant__ce9e55_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workitempartnerrole",
            index=models.Index(
                fields=["tenant", "role"], name="engagements_tenant__d2307b_idx"
            ),
        ),
    ]
