# Generated by Django 5.1.5 on 2025-07-27 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("engagements", "0002_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Assignment",
        ),
    ]
