# Generated by Django 5.1.5 on 2025-08-02 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("engagements", "0003_delete_assignment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="urgency",
        ),
    ]
