# Generated by Django 5.1.5 on 2025-07-23 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("engagements", "0003_activitylog_engagements_tenant__4a28de_idx_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WorkItemPartnerRole",
        ),
    ]
