# Generated by Django 5.1.5 on 2025-08-02 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engagements", "0005_workitemcategory_workitempriority_workitemstatus"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="workitem",
            new_name="engagements_status__56f047_idx",
            old_name="engagements_status_8eecb9_idx",
        ),
        migrations.RenameIndex(
            model_name="workitem",
            new_name="engagements_categor_37925b_idx",
            old_name="engagements_categor_47e530_idx",
        ),
        migrations.RenameIndex(
            model_name="workitem",
            new_name="engagements_priorit_158efd_idx",
            old_name="engagements_priorit_0b2a80_idx",
        ),
        migrations.RenameIndex(
            model_name="workitem",
            new_name="engagements_tenant__f338eb_idx",
            old_name="engagements_tenant__6b6101_idx",
        ),
        migrations.RenameIndex(
            model_name="workitem",
            new_name="engagements_tenant__aa07a1_idx",
            old_name="engagements_tenant__b8e7ff_idx",
        ),
        migrations.RenameIndex(
            model_name="workitem",
            new_name="engagements_tenant__e1fc24_idx",
            old_name="engagements_tenant__363847_idx",
        ),
        migrations.RenameIndex(
            model_name="workitem",
            new_name="engagements_status__b64202_idx",
            old_name="engagements_status_f28b5f_idx",
        ),
        migrations.RenameIndex(
            model_name="workitem",
            new_name="engagements_categor_b5a341_idx",
            old_name="engagements_categor_aad048_idx",
        ),
        migrations.AlterField(
            model_name="workitem",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="category_work_items",
                to="engagements.workitemcategory",
            ),
        ),
        migrations.AlterField(
            model_name="workitem",
            name="priority",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="priority_work_items",
                to="engagements.workitempriority",
            ),
        ),
        migrations.AlterField(
            model_name="workitem",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="status_work_items",
                to="engagements.workitemstatus",
            ),
        ),
    ]
