# Generated by Django 5.1.5 on 2025-07-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "engagements",
            "0005_rename_engagements_assigne_b947f3_idx_engagements_created_daa000_idx_and_more",
        ),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="activitylog",
            name="engagements_user_id_d47402_idx",
        ),
        migrations.RemoveIndex(
            model_name="activitylog",
            name="engagements_user_id_9d07b6_idx",
        ),
        migrations.RemoveIndex(
            model_name="attachment",
            name="engagements_uploade_2b66df_idx",
        ),
        migrations.RemoveIndex(
            model_name="attachment",
            name="engagements_uploade_326b4a_idx",
        ),
        migrations.RemoveIndex(
            model_name="comment",
            name="engagements_author__8af639_idx",
        ),
        migrations.RemoveIndex(
            model_name="comment",
            name="engagements_author__24af41_idx",
        ),
        migrations.RemoveField(
            model_name="activitylog",
            name="user",
        ),
        migrations.RemoveField(
            model_name="attachment",
            name="uploaded_by",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="author",
        ),
        migrations.RemoveField(
            model_name="job",
            name="assigned_team",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="reported_by",
        ),
        migrations.AlterField(
            model_name="ticket",
            name="ticket_number",
            field=models.CharField(
                blank=True, editable=False, max_length=50, null=True, unique=True
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["ticket_number"], name="engagements_ticket__d0834a_idx"
            ),
        ),
    ]
