# Generated by Django 5.1.5 on 2025-08-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "engagements",
            "0006_rename_engagements_status_8eecb9_idx_engagements_status__56f047_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="job_code",
            field=models.CharField(max_length=50),
        ),
    ]
