# Generated by Django 5.1.5 on 2025-07-24 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "engagements",
            "0006_remove_activitylog_engagements_user_id_d47402_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="work_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_to",
                to="engagements.workitem",
            ),
        ),
    ]
