# Generated by Django 5.1.5 on 2025-08-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engagements", "0007_alter_job_job_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="job_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
