# Generated by Django 5.1.5 on 2025-08-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engagements", "0008_alter_job_job_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="estimated_hours",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
