# Generated by Django 5.1.5 on 2025-08-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engagements", "0009_alter_job_estimated_hours"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="attachment",
            new_name="engagements_created_1d4caa_idx",
            old_name="engagements_created_2ad941_idx",
        ),
        migrations.RenameIndex(
            model_name="attachment",
            new_name="engagements_tenant__7716a1_idx",
            old_name="engagements_tenant__748b04_idx",
        ),
        migrations.RenameIndex(
            model_name="comment",
            new_name="engagements_created_779d71_idx",
            old_name="engagements_created_791320_idx",
        ),
        migrations.RenameIndex(
            model_name="comment",
            new_name="engagements_tenant__7e10c5_idx",
            old_name="engagements_tenant__310a42_idx",
        ),
        migrations.RenameIndex(
            model_name="workitem",
            new_name="engagements_created_e8c985_idx",
            old_name="engagements_created_fb5766_idx",
        ),
        migrations.AlterField(
            model_name="attachment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="created_by",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="updated_by",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="created_by",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="updated_by",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="workitem",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="workitem",
            name="created_by",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="workitem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="workitem",
            name="updated_by",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="workitemcategory",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="workitemcategory",
            name="created_by",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="workitemcategory",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="workitemcategory",
            name="updated_by",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="workitempriority",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="workitempriority",
            name="created_by",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="workitempriority",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="workitempriority",
            name="updated_by",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="workitemstatus",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="workitemstatus",
            name="created_by",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="workitemstatus",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="workitemstatus",
            name="updated_by",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
