# Generated by Django 5.1.5 on 2025-06-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diarium", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="mime_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
