# Generated by Django 5.1.5 on 2025-07-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diarium", "0002_attachment_mime_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("updated", "Updated"),
                    ("status_changed", "Status Changed"),
                    ("priority_changed", "Priority Changed"),
                    ("deadline_changed", "Deadline Changed"),
                    ("assigned", "Assigned"),
                    ("commented", "Commented"),
                    ("attachment_added", "Attachment Added"),
                ],
                max_length=20,
            ),
        ),
    ]
