# Generated by Django 5.1.5 on 2025-08-04 07:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("workitem", "Work Item"),
                            ("ticket", "Ticket"),
                            ("case", "Case"),
                            ("job", "Job"),
                            ("person", "Person"),
                            ("organization", "Organization"),
                            ("relation", "Relation"),
                            ("comment", "Comment"),
                            ("attachment", "Attachment"),
                            ("assignment", "Assignment"),
                            ("role", "Role"),
                            ("user", "User"),
                            ("tenant", "Tenant"),
                        ],
                        max_length=50,
                    ),
                ),
                ("entity_id", models.UUIDField()),
                ("entity_name", models.CharField(max_length=255)),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("deleted", "Deleted"),
                            ("status_changed", "Status Changed"),
                            ("priority_changed", "Priority Changed"),
                            ("assigned", "Assigned"),
                            ("commented", "Commented"),
                            ("viewed", "Viewed"),
                            ("exported", "Exported"),
                            ("imported", "Imported"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("archived", "Archived"),
                            ("restored", "Restored"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("change_summary", models.JSONField(blank=True, null=True)),
                ("old_values", models.JSONField(blank=True, null=True)),
                ("new_values", models.JSONField(blank=True, null=True)),
                ("session_id", models.CharField(blank=True, max_length=100, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                (
                    "business_process",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "compliance_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("financial", "Financial"),
                            ("operational", "Operational"),
                            ("security", "Security"),
                            ("privacy", "Privacy"),
                            ("regulatory", "Regulatory"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="low",
                        max_length=20,
                    ),
                ),
                ("is_immutable", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField()),
                ("label", models.CharField(max_length=100)),
                ("is_system", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "work_item_type",
                    models.CharField(
                        choices=[
                            ("ticket", "Ticket"),
                            ("case", "Case"),
                            ("job", "Job"),
                        ],
                        default="ticket",
                        max_length=50,
                    ),
                ),
                ("subscription_plan", models.CharField(default="free", max_length=50)),
                (
                    "subscription_status",
                    models.CharField(default="trial", max_length=50),
                ),
                (
                    "billing_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("billing_address", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
