# Generated by Django 5.1.5 on 2025-08-04 07:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_by", models.UUIDField(blank=True, db_index=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, db_index=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "work_item_type",
                    models.CharField(
                        choices=[
                            ("ticket", "Ticket"),
                            ("case", "Case"),
                            ("job", "Job"),
                        ],
                        default="ticket",
                        max_length=50,
                    ),
                ),
                ("subscription_plan", models.CharField(default="free", max_length=50)),
                (
                    "subscription_status",
                    models.CharField(default="trial", max_length=50),
                ),
                (
                    "billing_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("billing_address", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_by", models.UUIDField(blank=True, db_index=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, db_index=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("key", models.SlugField()),
                ("label", models.CharField(max_length=100)),
                ("is_system", models.BooleanField(default=False)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_system", True)),
                        fields=("key",),
                        name="unique_system_role_key",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_system", False)),
                        fields=("tenant", "key"),
                        name="unique_tenant_role_key",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_by", models.UUIDField(blank=True, db_index=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, db_index=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("workitem", "Work Item"),
                            ("ticket", "Ticket"),
                            ("case", "Case"),
                            ("job", "Job"),
                            ("person", "Person"),
                            ("organization", "Organization"),
                            ("relation", "Relation"),
                            ("comment", "Comment"),
                            ("attachment", "Attachment"),
                            ("assignment", "Assignment"),
                            ("role", "Role"),
                            ("user", "User"),
                            ("tenant", "Tenant"),
                        ],
                        max_length=50,
                    ),
                ),
                ("entity_id", models.UUIDField()),
                ("entity_name", models.CharField(max_length=255)),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("deleted", "Deleted"),
                            ("status_changed", "Status Changed"),
                            ("priority_changed", "Priority Changed"),
                            ("assigned", "Assigned"),
                            ("commented", "Commented"),
                            ("viewed", "Viewed"),
                            ("exported", "Exported"),
                            ("imported", "Imported"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("archived", "Archived"),
                            ("restored", "Restored"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("change_summary", models.JSONField(blank=True, null=True)),
                ("old_values", models.JSONField(blank=True, null=True)),
                ("new_values", models.JSONField(blank=True, null=True)),
                ("session_id", models.CharField(blank=True, max_length=100, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                (
                    "business_process",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "compliance_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("financial", "Financial"),
                            ("operational", "Operational"),
                            ("security", "Security"),
                            ("privacy", "Privacy"),
                            ("regulatory", "Regulatory"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="low",
                        max_length=20,
                    ),
                ),
                ("is_immutable", models.BooleanField(default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant"], name="core_auditl_tenant__acfac5_idx"
                    ),
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="core_auditl_entity__244637_idx",
                    ),
                    models.Index(
                        fields=["activity_type"], name="core_auditl_activit_ecf482_idx"
                    ),
                    models.Index(
                        fields=["created_by"], name="core_auditl_created_3fd614_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="core_auditl_created_dc23ea_idx"
                    ),
                    models.Index(
                        fields=["session_id"], name="core_auditl_session_7d1a57_idx"
                    ),
                    models.Index(
                        fields=["transaction_id"], name="core_auditl_transac_dfdcd0_idx"
                    ),
                    models.Index(
                        fields=["compliance_category"],
                        name="core_auditl_complia_238351_idx",
                    ),
                    models.Index(
                        fields=["risk_level"], name="core_auditl_risk_le_d7a24f_idx"
                    ),
                    models.Index(
                        fields=["tenant", "entity_type"],
                        name="core_auditl_tenant__b19d69_idx",
                    ),
                    models.Index(
                        fields=["tenant", "entity_type", "entity_id"],
                        name="core_auditl_tenant__239cb3_idx",
                    ),
                    models.Index(
                        fields=["tenant", "activity_type"],
                        name="core_auditl_tenant__3e24c4_idx",
                    ),
                    models.Index(
                        fields=["tenant", "created_by"],
                        name="core_auditl_tenant__987c21_idx",
                    ),
                    models.Index(
                        fields=["entity_type", "activity_type"],
                        name="core_auditl_entity__57cc7c_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "entity_type__in",
                                [
                                    "workitem",
                                    "ticket",
                                    "case",
                                    "job",
                                    "person",
                                    "organization",
                                    "relation",
                                    "comment",
                                    "attachment",
                                    "assignment",
                                    "role",
                                    "user",
                                    "tenant",
                                ],
                            )
                        ),
                        name="valid_entity_type",
                    )
                ],
            },
        ),
    ]
