# Generated by Django 5.1.5 on 2025-07-27 16:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="auditlog",
            name="valid_entity_type",
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="entity_type",
            field=models.CharField(
                choices=[
                    ("workitem", "Work Item"),
                    ("ticket", "Ticket"),
                    ("case", "Case"),
                    ("job", "Job"),
                    ("person", "Person"),
                    ("organization", "Organization"),
                    ("relation", "Relation"),
                    ("comment", "Comment"),
                    ("attachment", "Attachment"),
                    ("assignment", "Assignment"),
                    ("role", "Role"),
                    ("user", "User"),
                    ("tenant", "Tenant"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddConstraint(
            model_name="auditlog",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "entity_type__in",
                        [
                            "workitem",
                            "ticket",
                            "case",
                            "job",
                            "person",
                            "organization",
                            "relation",
                            "comment",
                            "attachment",
                            "assignment",
                            "role",
                            "user",
                            "tenant",
                        ],
                    )
                ),
                name="valid_entity_type",
            ),
        ),
    ]
