# Generated by Django 5.1.5 on 2025-07-27 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_add_user_tenant_entity_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to="core.tenant",
            ),
        ),
    ]
