# Generated by Django 5.1.5 on 2025-08-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_update_auditlog_tenant_cascade"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="core_auditl_created_3fd614_idx",
            old_name="core_auditl_created_62fcc5_idx",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="core_auditl_tenant__987c21_idx",
            old_name="core_auditl_tenant__6c9e4f_idx",
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="created_by",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="updated_by",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="role",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="role",
            name="created_by",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="role",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="role",
            name="updated_by",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="created_by",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="updated_by",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
